name = "hello-4s3ti"
license = "MIT"
licenselink = "https://github.com/4s3ti/hugo-theme-hello-4s3ti/blob/master/LICENSE.md"
description = "A simple theme for Hugo. That's it."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "4s3ti"
  homepage = "https://4s3ti.net"
  twitter = "https://twitter.com/4s3ti"

[original]
  name = "hello-friend"
  homepage = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
  repo = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
